'use strict';

require('./env_loader');

const fs = require('node:fs/promises');
const path = require('node:path');

const GITHUB_API = 'https://api.github.com';

function getHeaders() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN is not set. A personal access token is required to create pull requests.');
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'User-Agent': 'Project-Praetorian',
    'X-GitHub-Api-Version': '2022-11-28'
  };
}

async function githubFetch(url, options = {}) {
  const response = await fetch(url, { headers: getHeaders(), ...options });
  if (!response.ok) {
    const body = await response.text();
    throw new Error(`GitHub API error (${response.status}): ${body.slice(0, 500)}`);
  }
  return response.json();
}

async function forkRepo(owner, repo) {
  try {
    const fork = await githubFetch(`${GITHUB_API}/repos/${owner}/${repo}/forks`, {
      method: 'POST',
      headers: { ...getHeaders(), 'Content-Type': 'application/json' },
      body: JSON.stringify({ default_branch_only: true })
    });
    // Wait a moment for fork to be ready
    await new Promise((resolve) => setTimeout(resolve, 3000));
    return fork;
  } catch (err) {
    // Fork may already exist — try to find it
    const user = await githubFetch(`${GITHUB_API}/user`);
    try {
      return await githubFetch(`${GITHUB_API}/repos/${user.login}/${repo}`);
    } catch (_) {
      throw err;
    }
  }
}

async function createBranch(owner, repo, branchName, baseBranch) {
  const ref = await githubFetch(`${GITHUB_API}/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`);
  const sha = ref.object.sha;
  try {
    return await githubFetch(`${GITHUB_API}/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      headers: { ...getHeaders(), 'Content-Type': 'application/json' },
      body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha })
    });
  } catch (err) {
    // Branch may already exist — update it
    return await githubFetch(`${GITHUB_API}/repos/${owner}/${repo}/git/refs/heads/${branchName}`, {
      method: 'PATCH',
      headers: { ...getHeaders(), 'Content-Type': 'application/json' },
      body: JSON.stringify({ sha, force: true })
    });
  }
}

async function commitFile(owner, repo, branchName, filePath, content, message) {
  const existing = await githubFetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}?ref=${branchName}`)
    .catch(() => null);
  const body = {
    message,
    content: Buffer.from(content).toString('base64'),
    branch: branchName
  };
  if (existing && existing.sha) body.sha = existing.sha;
  return await githubFetch(`${GITHUB_API}/repos/${owner}/${repo}/contents/${filePath}`, {
    method: 'PUT',
    headers: { ...getHeaders(), 'Content-Type': 'application/json' },
    body: JSON.stringify(body)
  });
}

async function openPullRequest({ owner, repo, forkOwner, branchName, baseBranch, title, body }) {
  return await githubFetch(`${GITHUB_API}/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers: { ...getHeaders(), 'Content-Type': 'application/json' },
    body: JSON.stringify({
      title,
      body,
      head: `${forkOwner}:${branchName}`,
      base: baseBranch
    })
  });
}

/**
 * Full PR creation flow:
 * 1. Fork the repo
 * 2. Create a fix branch
 * 3. Commit the patched source file
 * 4. Open a PR with the remediation report
 */
async function createRemediationPR({ repoUrl, patchedFilePath, sourceRelPath, cve, packageName, remediationReport }) {
  const url = new URL(repoUrl);
  const parts = url.pathname.replace(/^\/+|\/+$/g, '').split('/');
  if (parts.length < 2) throw new Error('Invalid GitHub repo URL');
  const owner = parts[0];
  const repo = parts[1].replace(/\.git$/i, '');
  const sanitizedCve = (cve || 'fix').replace(/[^a-zA-Z0-9-]/g, '-').toLowerCase();
  const branchName = `interregnum/fix-${sanitizedCve}`;

  // 1. Fork
  const fork = await forkRepo(owner, repo);
  const forkOwner = fork.owner ? fork.owner.login : fork.full_name.split('/')[0];

  // 2. Get default branch
  const repoMeta = await githubFetch(`${GITHUB_API}/repos/${owner}/${repo}`);
  const baseBranch = repoMeta.default_branch || 'main';

  // 3. Create branch on fork
  await createBranch(forkOwner, repo, branchName, baseBranch);

  // 4. Commit patched file
  const patchedContent = await fs.readFile(patchedFilePath, 'utf8');
  await commitFile(forkOwner, repo, branchName, sourceRelPath, patchedContent,
    `fix(security): remediate ${cve || 'vulnerability'} in ${packageName}\n\nGenerated by The Interregnum Protocol`
  );

  // 5. Open PR
  const prBody = [
    `## 🛡️ Automated Security Remediation`,
    '',
    `**Package:** \`${packageName}\``,
    `**CVE:** \`${cve || 'N/A'}\``,
    `**Generated by:** [The Interregnum Protocol](https://github.com/ChinmayOnWeb/interregnum-protocol)`,
    '',
    '---',
    '',
    remediationReport || 'See attached remediation report for details.'
  ].join('\n');

  const pr = await openPullRequest({
    owner, repo, forkOwner, branchName, baseBranch,
    title: `fix(security): remediate ${cve || 'vulnerability'} in ${packageName}`,
    body: prBody
  });

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    forkUrl: fork.html_url,
    branchName
  };
}

module.exports = { createRemediationPR };
